<html>
    <style>
        .table{
            border:1px solid #ccc;
            border-collapse: collapse;
            width: 100%;
        }
        .table td,th{
            border: 1px solid #ccc;
            padding: 5px;
        }
        .text-center{
            text-align: center;
        }
        .bold{
            font-weight: bold;
        }
        .text-right{
            text-align: right;
        }
    </style>
    <?php 
    $colspan = (($dispatch[0]['is_catalytic_dispatch']=='No')) ? '4' : '3';
    $theadcolspan = (($dispatch[0]['is_catalytic_dispatch']=='No')) ? '5' : '4';
    $total2 =  (($dispatch[0]['is_catalytic_dispatch']=='No')) ? 'Total Gross' : 'Total Weight';
    $total1 =  (($dispatch[0]['is_catalytic_dispatch']=='No')) ? 'Total Net' : 'Total Units';
    ?>
    <table class="table">
        <tr>
            <td colspan="<?= $theadcolspan; ?>"><img src="<?= base_url($settings[4]['value'])?>"></td>
        </tr>
        <tr>
            <td class="text-center bold" colspan="<?= $theadcolspan; ?>">Dispatch</td>
        </tr>
        <tr>
            <td colspan="2"><b>Buyer:</b><br>
                <?= $buyer[0]['buyer_name'] ?>,<br>
                <?= $buyer[0]['company_name'] ?>,<br>
                <?= $buyer[0]['company_address'] ?>
            </td>
            <td colspan="<?= (($dispatch[0]['is_catalytic_dispatch']=='No')) ? '3' : '2' ?>">
                Dispatch No: <?= $dispatch[0]['dispatch_number']?><br>
                Dispatch Date: <?= displayDateInWords($dispatch[0]['dispatch_date']);?><br>
                Generated By: <?= $user[0]['first_name']?>
            </td>
        </tr>
        <tr>
            <th>S.No</th>
            <th>Product Name</th>
            <?php if($dispatch[0]['is_catalytic_dispatch']=='No') { ?>
            <th>Gross</th>
            <th>Tare</th>
            <th>Net</th>
            <?php }else{ ?> 
                <th>No Of Units</th>
                <th>Weight</th>
            <?php } ?>
        </tr>
        <?php
        if(!empty($dispatch_items)){ 
            $i=0;
        foreach($dispatch_items as $items){    
        ?>
        <tr>
            <td><?= ++$i; ?></td>
            <td><?= $items['product_name']; ?></td>
            <?php if($dispatch[0]['is_catalytic_dispatch']=='No') { ?>
            <td><?= $items['gross']; ?></td>
            <td><?= $items['tare']; ?></td>
            <td><?= $items['net']; ?></td>
            <?php }else{ ?>
            <td><?= $items['net']; ?></td>
            <td><?= $items['gross']; ?></td>
            <?php } ?>
        </tr>
        <?php } } ?>
        <tr>
            <td class="bold text-right" colspan="<?= $colspan; ?>"><?= $total1; ?> :</td>
            <td><?= $dispatch[0]['total_net'];?></td>
        </tr>
        <tr>
            <td class="bold text-right" colspan="<?= $colspan; ?>"><?= $total2; ?> :</td>
            <td><?= $dispatch[0]['total_gross'];?></td>
        </tr>
        <tr>
            <td class="bold">Note :</td>
            <td colspan="<?= $colspan; ?>"><?= $dispatch[0]['notes'];?></td>
        </tr>
    </table>
    <p class="bold">* This is computer generated dispatch slip and does not required signature.</p>
</html>